apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: frontend
    spec:
      containers:
      - name: frontend
        image: kishore8856/frontend:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: frontend
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5                
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 25
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80    # port on which service is exposed
      targetPort: 80   # port on which frontend container is listening