apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: frontend
    spec:
      containers:
      - name: frontend
        image: kishore8856/frontend:v2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5                
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 5
        volumeMounts:    # Mount the config map as a volume inside container
          - name: frontend-config
            mountPath: /etc/nginx/nginx.conf         # path inside container where config map file is to be mounted
            subPath: nginx.conf    # subpath tell k8s that nginx.conf alone should be mounted as file. Without this entire config map will be mounted as directory
      volumes:            # At this stage config map is mounted as volume inside pod
        - name: frontend-config
          configMap:
            name: frontend-cm

############
#NOTE: Always give subPath while mounting single file from config map. Otherwise entire config map will be mounted as directory. Especially for nginx it should be /etc/nginx/nginx.conf.
############
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80    # port on which service is exposed
      targetPort: 8080   # port on which frontend container is listening