apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: cart
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: cart
    spec:
      containers:
      - name: cart
        image: kishore8856/cart:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cart
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5                
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: cart
  ports:
    - protocol: TCP
      port: 8080    # port on which service is exposed
      targetPort: 8080   # port on which cart container is listening