apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # labels for deployment. These can be different from pod labels and selector. These are just for deployment identification
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  # selector to identify pods managed by deployment
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mongodb
  # pod template. RS controller uses this to create pods
  template:
    metadata:
      # pod template labels. Should match selector
      labels:
        project: roboshop
        environment: dev
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: kishore8856/mongodb:v2
      # Readiness probe is to check if container is ready to serve traffic. If this fails, pod is removed from service endpoints
      readinessProbe:
      tcpSocket:
        port: 27017
      initialDelaySeconds: 10   # Pod created, waaits for 10 secs, send TCP connection to port 27017
      periodSeconds: 5          # checks readiness every 5 seconds
      # Liveness probe is to check if pod is alive. If this fails, pod is restarted
      livenessProbe:
        tcpSocket:    # check via TCP socket. Just checks if container is listening on specified port
          port: 27017
        initialDelaySeconds: 5   # time to wait before performing first health check
        periodSeconds: 5         # frequency of health checks. Here every 5 seconds
      
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017    # port on which service is exposed
      targetPort: 27017   # port on which mongodb container is listening