apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: user
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: user
    spec:
      containers:
      - name: user
        image: kishore8856/user:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: user
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5                
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: user
  ports:
    - protocol: TCP
      port: 8080    # port on which service is exposed
      targetPort: 8080   # port on which user container is listening